### ISSUE TITLE
scriptBasePath

### ISSUE THREAD

**Issue by rdmueller** [rdmueller/asciidoc2confluence#8]
tried to fetch the scriptBasePath automatically - works for me, but does it also work for maven projects?

@aheusingfeld - could you give it a try?

**Comment by aheusingfeld** [comment]
It works with the configuration I proposed in the README file. This uses the gmaven-plus plugin which works like a charm. I'd say we should update the README for the other usage scenarios to tell the users explicitly how to use the script. :)

**Comment by rdmueller** [comment]
the maven solution broke the stand-alone solution since no scriptBasePath was defined
